### PR TITLE
64px armors in texture pack

### PR DESCRIPTION
**Pull request by leolegPremiumPlus**
Changes armor and armor trim textures from 16px to 64px and the doors and trapdoors

### CODE REVIEW

**Comment by leolegPremiumPlus** [comment]
Changes armor and armor trim textures from 16px to 64px

**Comment by fancyfinn9** [comment]
There is also a minor issue with all doors, mainly with the way they use the textures. It has existed beforehand as well, and is just made slightly more noticeable with the changes of mcl_door_*_bottompart.png to higher resolutions, but this issue probably does not belong in this PR.

**Review by fancyfinn9 — APPROVED** [review]
It's probably better without any re-textured heads now, it keeps consistency between the mob textures and the mob head ones.

**Comment by fancyfinn9** [comment]
Looks good to me 👍

**Comment by fancyfinn9** [comment]
Will merge in the next week or two along with other texture fixes.

**Review by loki0jma — APPROVED** [review]

**Pull request merged**
